// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Dev-time check: verify project ref in URL matches expected
(() => {
  try {
    const expectedRef = 'opdchkkmyjaccbkkdycl';
    const host = new URL(SUPABASE_URL).host; // e.g. opdchkkmyjaccbkkdycl.supabase.co
    if (!host.startsWith(expectedRef + '.')) {
      console.warn('[Supabase] Project ref mismatch. URL host =', host, 'expected to start with', expectedRef + '.');
    }
  } catch {}
})();